language: python
dist: xenial
services:
- docker
python:
  - "3.6"
  - "3.7"
env:
  # jobs running with older Django versions and SQLite
  - DJANGO_REL="django>=2.1,<2.2"
  - DJANGO_REL="django>=2.2,<2.3"
  # jobs running with dependent latest version and specific non-SQLite
  - DJANGO_REL="django>=3.0,<3.1" NITRATE_DB=sqlite
  - DJANGO_REL="django>=3.0,<3.1" NITRATE_DB=mysql
  - DJANGO_REL="django>=3.0,<3.1" NITRATE_DB=mariadb
  - DJANGO_REL="django>=3.0,<3.1" NITRATE_DB=postgres
install: pip install coveralls
script: |
  contrib/travis-ci/testrunner.py \
    --python-ver $TRAVIS_PYTHON_VERSION \
    --django-ver "$DJANGO_REL" \
    --nitrate-db ${NITRATE_DB:-sqlite} \
    src/tests
after_success: |
  [ -e .coverage ] && sudo chown travis:travis .coverage && \
    sqlite3 .coverage "UPDATE file SET path = REPLACE(path, '/code', '"$(pwd)"')" && \
    coveralls
jobs:
  include:
    - stage: Misc tests
      name: Check Python code style
      install: pip install tox
      script: tox -e flake8
    - name: Test build docs
      install: pip install tox
      script: tox -e docs
