language: python
dist: xenial
services:
- docker
matrix:
  include:
  # Django 2.1.x with Python 3.6 and 3.7
  # Also, run tests against Django 2.1.x, Python 3.6 and several database backends
  - python: "3.6"
    env: DJANGO_REL="django>=2.1,<2.2"
  - python: "3.6"
    env: DJANGO_REL="django>=2.1,<2.2" NITRATE_DB=mysql
  - python: "3.6"
    env: DJANGO_REL="django>=2.1,<2.2" NITRATE_DB=mariadb
  - python: "3.6"
    env: DJANGO_REL="django>=2.1,<2.2" NITRATE_DB=postgres
  - python: "3.7"
    env: DJANGO_REL="django>=2.1,<2.2"
  # Django 2.2.x with Python 3.6 and 3.7
  - python: "3.6"
    env: DJANGO_REL="django>=2.2,<2.3"
  - python: "3.7"
    env: DJANGO_REL="django>=2.2,<2.3"
install: pip install coveralls
script:
- contrib/travis-ci/testrunner.py --python-ver "$(python -V | sed 's/Python \([0-9]\+\)\.\([0-9]\+\)\.[0-9]\+/py\1\2/')" --django-ver "$DJANGO_REL" --nitrate-db ${NITRATE_DB:-sqlite} src/tests
after_success:
- sudo chown travis:travis .coverage
- sqlite3 .coverage "UPDATE file SET path = REPLACE(path, '/code', '"$(pwd)"')"
- coveralls
notifications:
  email:
    on_failure: change
    on_success: change
