version: "2"

# Please note that, this docker-compose is only for test prod docker image.
# If you would like to launch nitrate for development purpose, please use
# `docker-compose-dev.yml`.

services:
  db:
    image: "mariadb"
    volumes:
    - "nitrate_db_data:/var/lib/mysql"
    restart: always
    environment:
    - MYSQL_DATABASE=nitrate
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  web:
    depends_on:
    - db
    restart: always
    build:
      context: .
      dockerfile: ./docker/released/Dockerfile
    image: nitrate:4.3.2
    ports:
    - "8001:80"
    volumes:
    - "nitrate_uploads:/code/uploads"
    - "nitrate_httpd_logs:/var/log/httpd"
    environment:
      NITRATE_DB_ENGINE: mysql
      NITRATE_DB_HOST: db
      NITRATE_DB_PORT: 3306
      NITRATE_DB_NAME: nitrate
      NITRATE_DB_USER: root

# Run `docker inspect web` to see volume directory on host.

volumes:
  nitrate_db_data:
  nitrate_uploads:
  nitrate_httpd_logs:
